version: "3"
services:

  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80' 

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: redis:latest

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./express-ts-fib
    depends_on:
    - postgres
    - redis  
    volumes: 
      - /app/node_modules
      - ./express-ts-fib:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379      
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_PASSWORD=postgres_password
        
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./fib-react-ts
    volumes: 
      - /app/node_modules
      - ./fib-react-ts:/app    
    
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./fib-worker
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379  
    volumes: 
      - /app/node_modules
      - ./fib-worker:/app     